# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20101110135744) do

  create_table "loanapps", :force => true do |t|
    t.string   "loan_type"
    t.string   "line_of_credit_limit"
    t.string   "purpose_of_loan"
    t.string   "credit_increase_limit"
    t.string   "collateral_offered"
    t.string   "collateral_secured_limit"
    t.string   "owned_by"
    t.string   "type_of_credit"
    t.string   "single_life_insurance"
    t.string   "single_life_insurance_age"
    t.string   "joint_life_insurance"
    t.string   "joint_life_insurance_age"
    t.string   "credit_disability_insurance"
    t.string   "credit_disability_insurance_age"
    t.string   "applicant_name"
    t.string   "applicant_account_number"
    t.string   "applicant_ssn"
    t.string   "applicant_marital_status"
    t.string   "applicant_drivers_license"
    t.string   "applicant_drivers_license_state"
    t.string   "applicant_date_of_birth"
    t.string   "applicant_home_phone"
    t.string   "applicant_business_phone"
    t.string   "applicant_email_address"
    t.string   "applicant_mortgage"
    t.string   "applicant_mortgage_balance"
    t.string   "applicant_monthly_payment"
    t.string   "applicant_current_apr"
    t.string   "applicant_payment_responsible"
    t.string   "applicant_monthly_payments"
    t.string   "applicant_monthly_balances"
    t.string   "applicant_employer"
    t.string   "applicant_income"
    t.string   "applicant_income_type"
    t.string   "applicant_income_frequency"
    t.string   "applicant_other_income_source"
    t.string   "applicant_other_income"
    t.string   "applicant_other_income_frequency"
    t.string   "coapplicant_name"
    t.string   "coapplicant_account_number"
    t.string   "coapplicant_ssn"
    t.string   "coapplicant_marital_status"
    t.string   "coapplicant_drivers_license"
    t.string   "coapplicant_drivers_license_state"
    t.string   "coapplicant_date_of_birth"
    t.string   "coapplicant_home_phone"
    t.string   "coapplicant_business_phone"
    t.string   "coapplicant_email_address"
    t.string   "coapplicant_mortgage"
    t.string   "coapplicant_mortgage_balance"
    t.string   "coapplicant_monthly_payment"
    t.string   "coapplicant_current_apr"
    t.string   "coapplicant_payment_responsible"
    t.string   "coapplicant_monthly_payments"
    t.string   "coapplicant_monthly_balances"
    t.string   "coapplicant_employer"
    t.string   "coapplicant_income"
    t.string   "coapplicant_income_type"
    t.string   "coapplicant_income_frequency"
    t.string   "coapplicant_other_income_source"
    t.string   "coapplicant_other_income"
    t.string   "coapplicant_other_income_frequency"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "memberapps", :force => true do |t|
    t.string   "name"
    t.string   "salutation"
    t.string   "ssn"
    t.string   "date_of_birth"
    t.string   "joint_name"
    t.string   "joint_salutation"
    t.string   "joint_ssn"
    t.string   "joint_date_of_birth"
    t.string   "joint_privacy_code"
    t.string   "physical_address"
    t.string   "city"
    t.string   "state"
    t.integer  "zip"
    t.string   "mailing_address"
    t.string   "mailing_city"
    t.string   "mailing_state"
    t.integer  "mailing_zip"
    t.string   "home_phone"
    t.string   "business_phone"
    t.string   "membership_eligibility"
    t.string   "eligibility_description"
    t.string   "privacy_code"
    t.string   "email_address"
    t.string   "best_time_to_call"
    t.string   "us_citizen"
    t.string   "prime_savings"
    t.string   "other_savings"
    t.string   "mastermoney_debit_card"
    t.string   "phone_vision"
    t.string   "home_banking"
    t.string   "share_draft"
    t.string   "overdraft_protection"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "reqinfos", :force => true do |t|
    t.string   "first_name"
    t.string   "last_name"
    t.string   "address"
    t.string   "city"
    t.string   "state"
    t.integer  "zip"
    t.string   "email_address"
    t.string   "phone_number"
    t.string   "membership_application"
    t.string   "family_membership"
    t.string   "savings_account"
    t.string   "share_draft_account"
    t.string   "christmas_club_account"
    t.string   "money_market_account"
    t.string   "ira_savings"
    t.string   "ira_share_certificates"
    t.string   "share_certificates"
    t.string   "phone_vision"
    t.string   "overdraft_loan_information"
    t.string   "personal_loan_information"
    t.string   "automobile_loan_information"
    t.string   "heloc"
    t.string   "mortgage_loan_information"
    t.string   "visa_classic_card"
    t.string   "star_atm_card"
    t.string   "mastermoney_debit_card"
    t.string   "direct_deposit"
    t.string   "money_orders"
    t.string   "free_notary_service"
    t.string   "discount_tickets"
    t.string   "other_comments"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "visarequests", :force => true do |t|
    t.string   "visa_card_account"
    t.string   "account_type"
    t.string   "credit_increase_on_account"
    t.string   "account_number"
    t.string   "credit_limit_increase"
    t.string   "other_credit_limit"
    t.string   "applicant_name"
    t.string   "applicant_address"
    t.string   "applicant_city"
    t.string   "applicant_state"
    t.integer  "applicant_zip"
    t.string   "applicant_email_address"
    t.string   "applicant_gross_monthly_income"
    t.string   "applicant_ssn"
    t.string   "applicant_home_phone"
    t.string   "applicant_work_phone"
    t.string   "applicant_member_number"
    t.string   "applicant_date_of_birth"
    t.string   "applicant_employer"
    t.string   "applicant_income"
    t.string   "applicant_income_type"
    t.string   "applicant_income_frequency"
    t.string   "applicant_other_income_source"
    t.string   "applicant_other_income"
    t.string   "applicant_other_income_frequency"
    t.string   "coapplicant_name"
    t.string   "coapplicant_address"
    t.string   "coapplicant_city"
    t.string   "coapplicant_state"
    t.integer  "coapplicant_zip"
    t.string   "coapplicant_email_address"
    t.string   "coapplicant_gross_monthly_income"
    t.string   "coapplicant_ssn"
    t.string   "coapplicant_home_phone"
    t.string   "coapplicant_work_phone"
    t.string   "coapplicant_member_number"
    t.string   "coapplicant_date_of_birth"
    t.string   "coapplicant_employer"
    t.string   "coapplicant_income"
    t.string   "coapplicant_income_type"
    t.string   "coapplicant_income_frequency"
    t.string   "coapplicant_other_income_source"
    t.string   "coapplicant_other_income"
    t.string   "coapplicant_other_income_frequency"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
